### PR TITLE
Fix Firefox Drag'n'Drop Functionality

### LINKED ISSUE #293: [Bug] Drag and drop not working as expected
### Current behavior:
I am not sure if this is a bug: 
When I run  cypress test  with drag and drop variant nothing is uploaded. As far as I can see the problem is that in the dataTransfer object the'types' array is empty. My drag and drop implementation checks this property for including 'Files' type to allow uploads from drag and drop.

In general I think to simulate native behaviour the types proeprty should be set correctly.

Test code (partial):
`    cy.get(mediaCenter.upload.dropzone).attachFile('media.jpg', { subjectType: 'drag-n-drop' });
`

drop callback:

```
...
    drop(event) {
      const data = event.dataTransfer;
      // only accept file drag&drop. e.g. files from desktop
      if (data.types.indexOf('Files') === -1) {
        return;
      }
      this.$store.commit('upload/addMediaItemsFromFiles', data.files);
    },
...
```

This is just the dataTransfer object picked from ff console:
```
DataTransfer
​  dropEffect: "none"
​  effectAllowed: "none"
​  files: FileList [ File ]
​  items: DataTransferItemList { 0: DataTransferItem, length: 1 }
​  mozCursor: "auto"
​  mozSourceNode: null
​  mozUserCancelled: false
​  types: Array []
```
### Desired behavior:

The types array should include at least 'Files' when files are uploaded.

### Steps to reproduce: (app code and test code)

Just check the dataTransfer object by setting a breakpoint.

### Versions

Cypress: 6.5
Browser: Firefox
OS: ubuntu linux

### PR DESCRIPTION
**Pull request by michaeljaltamirano**
#### Checklist:

- [x] No linting issues
- [x] Commits are compliant with commitizen
- [x] CI tests have passed
- [x] Documentation updated

#### Summary of changes

#290 broke Firefox compatibility. This PR adds a specific check to see if the Cypress runner broswer is Firefox to manually add `'change'` into the drag'n'drop list of events because its presence was casing duplication for Chrome (see #276). 

Draft PR instead of ready for review because we should probably add tests that try and repro some of these issues (either Chrome duplication, or Firefox upload functionality broken) so that we don't play whack-a-mole with patch PRs. 

#### Linked issues

Closes #293

### CODE REVIEW

**Review by abramenal — APPROVED** [review]
Cool stuff!
I cannot recall the exact issue with tests in Firefox, but currently they are disabled. Will try to enable in in a separate PR

**Comment by abramenal** [comment]
Okay, I have finally brought Firefox tests back. Now, please rebase your branch with latest `main`, so it'll run whole testing suite based on latest configuration changes. Hope it'll be all green 🤞

**Comment by michaeljaltamirano** [comment]
> Okay, I have finally brought Firefox tests back. Now, please rebase your branch with latest `main`, so it'll run whole testing suite based on latest configuration changes. Hope it'll be all green 🤞

Looks green 🙏  Hopefully no more issues pop up 😬

**Comment by abramenal** [comment]
@all-contributors add @michaeljaltamirano for question and code

**Comment by abramenal** [comment]
Coool stuff, it is all green now!
https://github.com/abramenal/cypress-file-upload/actions/runs/751210777

Thanks a lot for your effort @michaeljaltamirano, really appreciate that! 💪

**Pull request merged**
