### PR TITLE
update command to accept multiple fixtures. fixes #203

### LINKED ISSUE #203: Allow uploading of multiple files outside of chaining `attachFile`
### Current behavior:

Users are able to upload multiple files by chaining `attachFile` methods.

**Example from docs**
```javascript
cy.get('[data-cy="file-input"]')
  .attachFile(yourFixturePath)
  .attachFile(yourBestPicture);
```

### Desired behavior:

The above behavior assumes a static number of known files and removes flexibility from previous versions of passing an array of files. It would be nice to have this feature re-implemented in some way.

**Example with old implementation (trimmed down for brevity)**
```javascript
// uploadMultipleFiles.js

const PDF_FILE = 'Test.pdf';
const DOCX_FILE = 'Test.docx';
const DROPZONE_ELEMENT = '.very-specific-class-name';

Cypress.Commands.add('uploadMultipleFiles', ({ count = 2, type = 'docx' }) => {
  const files = [];

  const fileTypes = { docx: DOCX_FILE, pdf: PDF_FILE };

  for (let index = 0; index < count; index++) {
    if (index % 2 === 0) {
      files.push(fileTypes[type] || fileTypes.docx);
    } else {
      files.push(fileTypes[type] || fileTypes.pdf);
    }
  }

  cy.get(DROPZONE_ELEMENT).attachFile(files, processingOptions);
};

// test.spec.js

describe('A good test', () => {
  it('Should upload 3 files', () => {
    cy.uploadMultipleFiles({ count: 3 });
  };

  it('Should upload 10 DOCX files', () => {
    cy.uploadMultipleFiles({ count: 10, type: 'docx' });
  };
});
```

### Versions

**OS**: macOS Mojave 10.14.6
**Browser**: Chrome 81.0.4044.138
**`cypress`**: `^4.5.0`
**`cypress-file-upload`**: `^4.0.6`

### PR DESCRIPTION
**Pull request by Hypercubed**
This PR seperates out events from attaching files.  The `attachFile` now accepts an array of fixtures.  Each fixture is attached sequentually then the events are trigger.

Added tests and verified in `recipes/angularjs-ng-file-upload`.

Closes #203

### CODE REVIEW

**Comment by abramenal** [comment]
@Hypercubed thanks for submitting MR! Looks good 👍 
I will need 1-2 days to add more tests to other frameworks to make sure it's being tested on every setup.

Also it is worth updating README.md with simple snippet to illustrate how this should work.

@all-contributors add @Hypercubed for code

**Comment by abramenal** [comment]
@all-contributors add @Hypercubed for code

**Comment by abramenal** [comment]
Unfortunately this is not working with react drag-n-drop

**Comment by Hypercubed** [comment]
I'm not sure I undetstand what you mean by "cannot trigger valid event containing all the files".  Does this mean it break react drag-n-drop entirely or only when passing multiple fixtures.  I wonder if it ever work with the older version.

**Comment by abramenal** [comment]
It breaks entirely regardless of files count. You can reproduce it when running examples/react-dropzone repo tests – there you can tweak `import 'cypress-file-upload'` to use your local version `import '../../../../src/index'`.

I planned to look into it this weekend, but feel free to investigate if you have time.

**Comment by tommy-anderson** [comment]
Hey there, @abramenal , @Hypercubed any idea when this will happen?

Our project relies heavily on uploading files and we just started updating from cypress 4.12.1 to cypress 6.4.1 so naturally need to update the cypress-file-upload plugin. Would hate to leave the the mulitple-images upload test cases hanging.

Sadly I don't have enough technical background to dive into the issues myself.

**Comment by abramenal** [comment]
Hi @tommy-anderson,
I know this is painful, really appreciate your patience on that.

I see @paulblyth submitted a PR, I am happy to look at it during weekend. Hopefully this will work just fine so I can release it quickly. Will keep this PR posted as well.

**Comment by abramenal** [comment]
#251 is merged, so closing this one. Thanks anyways, appreciate your effort and welcome to the contributors list ❤️

**Pull request closed without merging**
