### PR TITLE
Add cypress log command

### PR DESCRIPTION
**Pull request by DragorWW**
- remove unimportant command (window, wrap)
- add cypress custom comand upload

**before**:
image

**after**:
input:
image
drop: 
image

on click:
image

### CODE REVIEW

**Comment by abramenal** [comment]
What I would also think on is how to make "drop" logging more fancy, see Object{10} there. Any idea what is that?

**Comment by DragorWW** [comment]
@abramenal this behavior cypres itself, variants:
- consider it normal
- remove log for `cy.trigger()` (and maybe add custom drop log)

I saved the trigger logging, as I considered it important and visual.

**Comment by abramenal** [comment]
Agree with that. May I kindly ask you to resolve conflicts to let this go?
I expect releasing this (& maybe something else) in v3.0.6 this weekend.

**Comment by abramenal** [comment]
@allcontributors[bot] add @DragorWW for code

**Pull request merged**
