### PR TITLE
Add link to allowed encodings to README

### PR DESCRIPTION
**Pull request by JesseDeBruijne**
It took me quite some time to find what exact value to pass through there (turned out I need lowercase).

This would help people find the right string value faster.

### CODE REVIEW

**Comment by abramenal** [comment]
Hi @JesseDeBruijne 
Thanks for contribution!

Isn't that the same what is desribed here?
https://docs.cypress.io/api/commands/fixture.html#Arguments

**Comment by JesseDeBruijne** [comment]
> Isn't that the same what is desribed here?
> https://docs.cypress.io/api/commands/fixture.html#Arguments

Yes it seems so! I was looking through the GitHub typings to find them so that's where I ended up. Feel free to choose either link, I just thought giving people a shorthand was a good idea.

**Comment by abramenal** [comment]
There's 3rd option: deep link into the code 😈 
https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js#L29

What do you think? Is it worth pointing here instead? This way if a new encoding is added with this plugin, we all see it immediately

**Comment by JesseDeBruijne** [comment]
That's a good one! (can't believe I missed that)

I feel like that's the best option since it always reflects the truth and doesn't rely on other updates, I will change the PR.

**Comment by abramenal** [comment]
Perfect! Thank you!
@all-contributors add @JesseDeBruijne for doc

**Pull request merged**
