### PR TITLE
feat: support FileList native API

### LINKED ISSUE #133: [Bug] How to upload to Angular's ngx-dropzone
### Current behavior:

Hi!

I'm trying to use the provided examples to upload a file via drag n' drop to Angular's `ngx-dropzone`:

```javascript
    const fileName = 'import-contacts-short.csv';

    cy.fixture(fileName).then(fileContent => {
      cy.get('[data-testid="dropzone"]').upload(
        { fileContent, fileName, mimeType: 'text/csv' },
        { subjectType: 'drag-n-drop' },
      );
    });
```

But I'm facing the following error:

image

This suggests that I should be passing a `FileList`, as `.item` is a property of this class, but I can't, since it is a readonly constructor. If `ngx-dropzone` is meant to be supported, is there any workaround to this?

Thanks in advance.

### Desired behavior:

`upload` should support sending files via a `FileList`

### PR DESCRIPTION
**Pull request by abramenal**
Closes #133

### CODE REVIEW

**Comment by topaxi** [comment]
This broke our tests when using with https://fineuploader.com/. The library is no longer supported though, so I'm not sure whether there is a more appropriate way to still support it and make the new use-case work.

I realize that maybe legacy systems is not a priority of this library, but we are sadly no longer able to update `cypress-file-upload` until we replace the above library (maybe others have similar issues).

Having a feature as a bugfix release was a bit surprising to me.

**Comment by abramenal** [comment]
@topaxi `FileList` API was already used for plain inputs so using it for drag-n-drop was quite straightforward. Are you sure this is not supported at all?
Maybe it's better to create a separate issue and link with this PR, maybe we can avoid this by using something other.

**Comment by topaxi** [comment]
I assume this is caused due to a now missing `types: ['Files']` prop on the `DataTransfer` object. The property is only set on the `dragStart` event and is readonly according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/types), I'm currently trying whether I can circumvent this somehow.

Redefining the property via `Object.defineProperty` didn't work, I'm now trying to use either `Object.create()` or mess with the prototype 🙈.

**Comment by abramenal** [comment]
@topaxi using`DataTransfer` API adds `types: ['Files']` to the object automatically, so I think it should be something else:

```
const file = new File(["foo"], "foo.txt", {
  type: "text/plain",
});
const dt = new DataTransfer();
dt.items.add(file);
console.log(dt.types);
```

**Comment by topaxi** [comment]
Yes, I noticed, everything seems fine when looking at the object, yet the tests fail and reverting to a plain array works 😭. Might be some weird internal issue with the other library.

I'll report back in case I find a way to fix the issue, for now we'll revert back to `3.5.0`.

**Comment by abramenal** [comment]
@topaxi it would be really good to understand the root cause. If the issue could affect other users (which may not use this specific plugin) I am happy to fix this.

Thank you!

**Comment by yonigibbs** [comment]
I've just logged #138, which might possibly be related here, not sure. In that issue, reverting to a plain array (e.g. by downgrading to 3.5.0) resolved the issue.

**Pull request merged**
